#!/usr/bin/python
import requests
import os

api_key = "INSERT YOUR KEY HERE"

r = requests.get("https://api.torn.com/torn/?selections=items&key=" + api_key)
data = r.json()
itemid = 1
itemname = raw_input("Name? ")

while itemid <= 981:
	if data["items"][str(itemid)]["name"] == itemname:
		priceresolve = 'curl -s https://api.torn.com/market/' + str(itemid) + '?key=' + api_key + ' | sed "s/,/\\n/g" | grep cost | sed "s/\\".\+\\"/ /g" | sed "s/ ://g" | sed "s/{//" | head -10'
		os.system(priceresolve)
		exit(0)
	itemid = itemid + 1
